// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: a2a.proto

/* eslint-disable */

export const protobufPackage = "lf.a2a.v1";

/** Older protoc compilers don't understand edition yet. */

/** Defines the possible lifecycle states of a `Task`. */
export enum TaskState {
  /** TASK_STATE_UNSPECIFIED - The task is in an unknown or indeterminate state. */
  TASK_STATE_UNSPECIFIED = 0,
  /** TASK_STATE_SUBMITTED - Indicates that a task has been successfully submitted and acknowledged. */
  TASK_STATE_SUBMITTED = 1,
  /** TASK_STATE_WORKING - Indicates that a task is actively being processed by the agent. */
  TASK_STATE_WORKING = 2,
  /** TASK_STATE_COMPLETED - Indicates that a task has finished successfully. This is a terminal state. */
  TASK_STATE_COMPLETED = 3,
  /** TASK_STATE_FAILED - Indicates that a task has finished with an error. This is a terminal state. */
  TASK_STATE_FAILED = 4,
  /** TASK_STATE_CANCELED - Indicates that a task was canceled before completion. This is a terminal state. */
  TASK_STATE_CANCELED = 5,
  /** TASK_STATE_INPUT_REQUIRED - Indicates that the agent requires additional user input to proceed. This is an interrupted state. */
  TASK_STATE_INPUT_REQUIRED = 6,
  /**
   * TASK_STATE_REJECTED - Indicates that the agent has decided to not perform the task.
   * This may be done during initial task creation or later once an agent
   * has determined it can't or won't proceed. This is a terminal state.
   */
  TASK_STATE_REJECTED = 7,
  /** TASK_STATE_AUTH_REQUIRED - Indicates that authentication is required to proceed. This is an interrupted state. */
  TASK_STATE_AUTH_REQUIRED = 8,
  UNRECOGNIZED = -1,
}

export function taskStateFromJSON(object: any): TaskState {
  switch (object) {
    case 0:
    case "TASK_STATE_UNSPECIFIED":
      return TaskState.TASK_STATE_UNSPECIFIED;
    case 1:
    case "TASK_STATE_SUBMITTED":
      return TaskState.TASK_STATE_SUBMITTED;
    case 2:
    case "TASK_STATE_WORKING":
      return TaskState.TASK_STATE_WORKING;
    case 3:
    case "TASK_STATE_COMPLETED":
      return TaskState.TASK_STATE_COMPLETED;
    case 4:
    case "TASK_STATE_FAILED":
      return TaskState.TASK_STATE_FAILED;
    case 5:
    case "TASK_STATE_CANCELED":
      return TaskState.TASK_STATE_CANCELED;
    case 6:
    case "TASK_STATE_INPUT_REQUIRED":
      return TaskState.TASK_STATE_INPUT_REQUIRED;
    case 7:
    case "TASK_STATE_REJECTED":
      return TaskState.TASK_STATE_REJECTED;
    case 8:
    case "TASK_STATE_AUTH_REQUIRED":
      return TaskState.TASK_STATE_AUTH_REQUIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TaskState.UNRECOGNIZED;
  }
}

export function taskStateToJSON(object: TaskState): string {
  switch (object) {
    case TaskState.TASK_STATE_UNSPECIFIED:
      return "TASK_STATE_UNSPECIFIED";
    case TaskState.TASK_STATE_SUBMITTED:
      return "TASK_STATE_SUBMITTED";
    case TaskState.TASK_STATE_WORKING:
      return "TASK_STATE_WORKING";
    case TaskState.TASK_STATE_COMPLETED:
      return "TASK_STATE_COMPLETED";
    case TaskState.TASK_STATE_FAILED:
      return "TASK_STATE_FAILED";
    case TaskState.TASK_STATE_CANCELED:
      return "TASK_STATE_CANCELED";
    case TaskState.TASK_STATE_INPUT_REQUIRED:
      return "TASK_STATE_INPUT_REQUIRED";
    case TaskState.TASK_STATE_REJECTED:
      return "TASK_STATE_REJECTED";
    case TaskState.TASK_STATE_AUTH_REQUIRED:
      return "TASK_STATE_AUTH_REQUIRED";
    case TaskState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Defines the sender of a message in A2A protocol communication. */
export enum Role {
  /** ROLE_UNSPECIFIED - The role is unspecified. */
  ROLE_UNSPECIFIED = 0,
  /** ROLE_USER - The message is from the client to the server. */
  ROLE_USER = 1,
  /** ROLE_AGENT - The message is from the server to the client. */
  ROLE_AGENT = 2,
  UNRECOGNIZED = -1,
}

export function roleFromJSON(object: any): Role {
  switch (object) {
    case 0:
    case "ROLE_UNSPECIFIED":
      return Role.ROLE_UNSPECIFIED;
    case 1:
    case "ROLE_USER":
      return Role.ROLE_USER;
    case 2:
    case "ROLE_AGENT":
      return Role.ROLE_AGENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Role.UNRECOGNIZED;
  }
}

export function roleToJSON(object: Role): string {
  switch (object) {
    case Role.ROLE_UNSPECIFIED:
      return "ROLE_UNSPECIFIED";
    case Role.ROLE_USER:
      return "ROLE_USER";
    case Role.ROLE_AGENT:
      return "ROLE_AGENT";
    case Role.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Configuration of a send message request. */
export interface SendMessageConfiguration {
  /**
   * A list of media types the client is prepared to accept for response parts.
   * Agents SHOULD use this to tailor their output.
   */
  acceptedOutputModes: string[];
  /**
   * Configuration for the agent to send push notifications for task updates.
   * Task id should be empty when sending this configuration in a `SendMessage` request.
   */
  taskPushNotificationConfig:
    | TaskPushNotificationConfig
    | undefined;
  /**
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   */
  historyLength?:
    | number
    | undefined;
  /**
   * If `true`, the operation returns immediately after creating the task,
   * even if processing is still in progress.
   * If `false` (default), the operation MUST wait until the task reaches a
   * terminal (`COMPLETED`, `FAILED`, `CANCELED`, `REJECTED`) or interrupted
   * (`INPUT_REQUIRED`, `AUTH_REQUIRED`) state before returning.
   */
  returnImmediately: boolean;
}

/**
 * `Task` is the core unit of action for A2A. It has a current status
 * and when results are created for the task they are stored in the
 * artifact. If there are multiple turns for a task, these are stored in
 * history.
 */
export interface Task {
  /**
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   */
  id: string;
  /**
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages).
   */
  contextId: string;
  /** The current status of a `Task`, including `state` and a `message`. */
  status:
    | TaskStatus
    | undefined;
  /** A set of output artifacts for a `Task`. */
  artifacts: Artifact[];
  /**
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   */
  history: Message[];
  /**
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   */
  metadata: { [key: string]: any } | undefined;
}

/** A container for the status of a task */
export interface TaskStatus {
  /** The current state of this task. */
  state: TaskState;
  /** A message associated with the status. */
  message:
    | Message
    | undefined;
  /**
   * ISO 8601 Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   */
  timestamp: string | undefined;
}

/**
 * `Part` represents a container for a section of communication content.
 * Parts can be purely textual, some sort of file (image, video, etc) or
 * a structured data blob (i.e. JSON).
 */
export interface Part {
  content?:
    | //
    /** The string content of the `text` part. */
    { $case: "text"; value: string }
    | //
    /** The `raw` byte content of a file. In JSON serialization, this is encoded as a base64 string. */
    { $case: "raw"; value: Buffer }
    | //
    /** A `url` pointing to the file's content. */
    { $case: "url"; value: string }
    | //
    /** Arbitrary structured `data` as a JSON value (object, array, string, number, boolean, or null). */
    { $case: "data"; value: any | undefined }
    | undefined;
  /** Optional. metadata associated with this part. */
  metadata:
    | { [key: string]: any }
    | undefined;
  /** An optional `filename` for the file (e.g., "document.pdf"). */
  filename: string;
  /**
   * The `media_type` (MIME type) of the part content (e.g., "text/plain", "application/json", "image/png").
   * This field is available for all part types.
   */
  mediaType: string;
}

/**
 * `Message` is one unit of communication between client and server. It can be
 * associated with a context and/or a task. For server messages, `context_id` must
 * be provided, and `task_id` only if a task was created. For client messages, both
 * fields are optional, with the caveat that if both are provided, they have to
 * match (the `context_id` has to be the one that is set on the task). If only
 * `task_id` is provided, the server will infer `context_id` from it.
 */
export interface Message {
  /** The unique identifier (e.g. UUID) of the message. This is created by the message creator. */
  messageId: string;
  /** Optional. The context id of the message. If set, the message will be associated with the given context. */
  contextId: string;
  /** Optional. The task id of the message. If set, the message will be associated with the given task. */
  taskId: string;
  /** Identifies the sender of the message. */
  role: Role;
  /** Parts is the container of the message content. */
  parts: Part[];
  /** Optional. Any metadata to provide along with the message. */
  metadata:
    | { [key: string]: any }
    | undefined;
  /** The URIs of extensions that are present or contributed to this Message. */
  extensions: string[];
  /** A list of task IDs that this message references for additional context. */
  referenceTaskIds: string[];
}

/** Artifacts represent task outputs. */
export interface Artifact {
  /** Unique identifier (e.g. UUID) for the artifact. It must be unique within a task. */
  artifactId: string;
  /** A human readable name for the artifact. */
  name: string;
  /** Optional. A human readable description of the artifact. */
  description: string;
  /** The content of the artifact. Must contain at least one part. */
  parts: Part[];
  /** Optional. Metadata included with the artifact. */
  metadata:
    | { [key: string]: any }
    | undefined;
  /** The URIs of extensions that are present or contributed to this Artifact. */
  extensions: string[];
}

/** An event sent by the agent to notify the client of a change in a task's status. */
export interface TaskStatusUpdateEvent {
  /** The ID of the task that has changed. */
  taskId: string;
  /** The ID of the context that the task belongs to. */
  contextId: string;
  /** The new status of the task. */
  status:
    | TaskStatus
    | undefined;
  /** Optional. Metadata associated with the task update. */
  metadata: { [key: string]: any } | undefined;
}

/** A task delta where an artifact has been generated. */
export interface TaskArtifactUpdateEvent {
  /** The ID of the task for this artifact. */
  taskId: string;
  /** The ID of the context that this task belongs to. */
  contextId: string;
  /** The artifact that was generated or updated. */
  artifact:
    | Artifact
    | undefined;
  /**
   * If true, the content of this artifact should be appended to a previously
   * sent artifact with the same ID.
   */
  append: boolean;
  /** If true, this is the final chunk of the artifact. */
  lastChunk: boolean;
  /** Optional. Metadata associated with the artifact update. */
  metadata: { [key: string]: any } | undefined;
}

/** Defines authentication details, used for push notifications. */
export interface AuthenticationInfo {
  /**
   * HTTP Authentication Scheme from the [IANA registry](https://www.iana.org/assignments/http-authschemes/).
   * Examples: `Bearer`, `Basic`, `Digest`.
   * Scheme names are case-insensitive per [RFC 9110 Section 11.1](https://www.rfc-editor.org/rfc/rfc9110#section-11.1).
   */
  scheme: string;
  /** Push Notification credentials. Format depends on the scheme (e.g., token for Bearer). */
  credentials: string;
}

/**
 * Declares a combination of a target URL, transport and protocol version for interacting with the agent.
 * This allows agents to expose the same functionality over multiple protocol binding mechanisms.
 */
export interface AgentInterface {
  /**
   * The URL where this interface is available. Must be a valid absolute HTTPS URL in production.
   * Example: "https://api.example.com/a2a/v1", "https://grpc.example.com/a2a"
   */
  url: string;
  /**
   * The protocol binding supported at this URL. This is an open form string, to be
   * easily extended for other protocol bindings. The core ones officially
   * supported are `JSONRPC`, `GRPC` and `HTTP+JSON`.
   */
  protocolBinding: string;
  /** Tenant ID to be used in the request when calling the agent. */
  tenant: string;
  /**
   * The version of the A2A protocol this interface exposes.
   * Use the latest supported minor version per major version.
   * Examples: "0.3", "1.0"
   */
  protocolVersion: string;
}

/**
 * A self-describing manifest for an agent. It provides essential
 * metadata including the agent's identity, capabilities, skills, supported
 * communication methods, and security requirements.
 * Next ID: 20
 */
export interface AgentCard {
  /**
   * A human readable name for the agent.
   * Example: "Recipe Agent"
   */
  name: string;
  /**
   * A human-readable description of the agent, assisting users and other agents
   * in understanding its purpose.
   * Example: "Agent that helps users with recipes and cooking."
   */
  description: string;
  /** Ordered list of supported interfaces. The first entry is preferred. */
  supportedInterfaces: AgentInterface[];
  /** The service provider of the agent. */
  provider:
    | AgentProvider
    | undefined;
  /**
   * The version of the agent.
   * Example: "1.0.0"
   */
  version: string;
  /** A URL providing additional documentation about the agent. */
  documentationUrl?:
    | string
    | undefined;
  /** A2A Capability set supported by the agent. */
  capabilities:
    | AgentCapabilities
    | undefined;
  /** The security scheme details used for authenticating with this agent. */
  securitySchemes: { [key: string]: SecurityScheme };
  /** Security requirements for contacting the agent. */
  securityRequirements: SecurityRequirement[];
  /**
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * The set of interaction modes that the agent supports across all skills.
   * This can be overridden per skill. Defined as media types.
   */
  defaultInputModes: string[];
  /** The media types supported as outputs from this agent. */
  defaultOutputModes: string[];
  /**
   * Skills represent the abilities of an agent.
   * It is largely a descriptive concept but represents a more focused set of behaviors that the
   * agent is likely to succeed at.
   */
  skills: AgentSkill[];
  /** JSON Web Signatures computed for this `AgentCard`. */
  signatures: AgentCardSignature[];
  /** Optional. A URL to an icon for the agent. */
  iconUrl?: string | undefined;
}

export interface AgentCard_SecuritySchemesEntry {
  key: string;
  value: SecurityScheme | undefined;
}

/** Represents the service provider of an agent. */
export interface AgentProvider {
  /**
   * A URL for the agent provider's website or relevant documentation.
   * Example: "https://ai.google.dev"
   */
  url: string;
  /**
   * The name of the agent provider's organization.
   * Example: "Google"
   */
  organization: string;
}

/** Defines optional capabilities supported by an agent. */
export interface AgentCapabilities {
  /** Indicates if the agent supports streaming responses. */
  streaming?:
    | boolean
    | undefined;
  /** Indicates if the agent supports sending push notifications for asynchronous task updates. */
  pushNotifications?:
    | boolean
    | undefined;
  /** A list of protocol extensions supported by the agent. */
  extensions: AgentExtension[];
  /** Indicates if the agent supports providing an extended agent card when authenticated. */
  extendedAgentCard?: boolean | undefined;
}

/** A declaration of a protocol extension supported by an Agent. */
export interface AgentExtension {
  /** The unique URI identifying the extension. */
  uri: string;
  /** A human-readable description of how this agent uses the extension. */
  description: string;
  /** If true, the client must understand and comply with the extension's requirements. */
  required: boolean;
  /** Optional. Extension-specific configuration parameters. */
  params: { [key: string]: any } | undefined;
}

/** Represents a distinct capability or function that an agent can perform. */
export interface AgentSkill {
  /** A unique identifier for the agent's skill. */
  id: string;
  /** A human-readable name for the skill. */
  name: string;
  /** A detailed description of the skill. */
  description: string;
  /** A set of keywords describing the skill's capabilities. */
  tags: string[];
  /** Example prompts or scenarios that this skill can handle. */
  examples: string[];
  /** The set of supported input media types for this skill, overriding the agent's defaults. */
  inputModes: string[];
  /** The set of supported output media types for this skill, overriding the agent's defaults. */
  outputModes: string[];
  /** Security schemes necessary for this skill. */
  securityRequirements: SecurityRequirement[];
}

/**
 * AgentCardSignature represents a JWS signature of an AgentCard.
 * This follows the JSON format of an RFC 7515 JSON Web Signature (JWS).
 */
export interface AgentCardSignature {
  /**
   * (-- api-linter: core::0140::reserved-words=disabled
   *     aip.dev/not-precedent: Backwards compatibility --)
   * Required. The protected JWS header for the signature. This is always a
   * base64url-encoded JSON object.
   */
  protected: string;
  /** Required. The computed signature, base64url-encoded. */
  signature: string;
  /** The unprotected JWS header values. */
  header: { [key: string]: any } | undefined;
}

/** A container associating a push notification configuration with a specific task. */
export interface TaskPushNotificationConfig {
  /** Optional. Tenant ID. */
  tenant: string;
  /**
   * The push notification configuration details.
   * A unique identifier (e.g. UUID) for this push notification configuration.
   */
  id: string;
  /** The ID of the task this configuration is associated with. */
  taskId: string;
  /** The URL where the notification should be sent. */
  url: string;
  /** A token unique for this task or session. */
  token: string;
  /** Authentication information required to send the notification. */
  authentication: AuthenticationInfo | undefined;
}

/**
 * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
 * A list of strings.
 */
export interface StringList {
  /** The individual string values. */
  list: string[];
}

/** Defines the security requirements for an agent. */
export interface SecurityRequirement {
  /** A map of security schemes to the required scopes. */
  schemes: { [key: string]: StringList };
}

export interface SecurityRequirement_SchemesEntry {
  key: string;
  value: StringList | undefined;
}

/**
 * Defines a security scheme that can be used to secure an agent's endpoints.
 * This is a discriminated union type based on the OpenAPI 3.2 Security Scheme Object.
 * See: https://spec.openapis.org/oas/v3.2.0.html#security-scheme-object
 */
export interface SecurityScheme {
  scheme?:
    | //
    /** API key-based authentication. */
    { $case: "apiKeySecurityScheme"; value: APIKeySecurityScheme }
    | //
    /** HTTP authentication (Basic, Bearer, etc.). */
    { $case: "httpAuthSecurityScheme"; value: HTTPAuthSecurityScheme }
    | //
    /** OAuth 2.0 authentication. */
    { $case: "oauth2SecurityScheme"; value: OAuth2SecurityScheme }
    | //
    /** OpenID Connect authentication. */
    { $case: "openIdConnectSecurityScheme"; value: OpenIdConnectSecurityScheme }
    | //
    /** Mutual TLS authentication. */
    { $case: "mtlsSecurityScheme"; value: MutualTlsSecurityScheme }
    | undefined;
}

/** Defines a security scheme using an API key. */
export interface APIKeySecurityScheme {
  /** An optional description for the security scheme. */
  description: string;
  /** The location of the API key. Valid values are "query", "header", or "cookie". */
  location: string;
  /** The name of the header, query, or cookie parameter to be used. */
  name: string;
}

/** Defines a security scheme using HTTP authentication. */
export interface HTTPAuthSecurityScheme {
  /** An optional description for the security scheme. */
  description: string;
  /**
   * The name of the HTTP Authentication scheme to be used in the Authorization header,
   * as defined in RFC7235 (e.g., "Bearer").
   * This value should be registered in the IANA Authentication Scheme registry.
   */
  scheme: string;
  /**
   * A hint to the client to identify how the bearer token is formatted (e.g., "JWT").
   * Primarily for documentation purposes.
   */
  bearerFormat: string;
}

/** Defines a security scheme using OAuth 2.0. */
export interface OAuth2SecurityScheme {
  /** An optional description for the security scheme. */
  description: string;
  /** An object containing configuration information for the supported OAuth 2.0 flows. */
  flows:
    | OAuthFlows
    | undefined;
  /**
   * URL to the OAuth2 authorization server metadata [RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414).
   * TLS is required.
   */
  oauth2MetadataUrl: string;
}

/** Defines a security scheme using OpenID Connect. */
export interface OpenIdConnectSecurityScheme {
  /** An optional description for the security scheme. */
  description: string;
  /** The [OpenID Connect Discovery URL](https://openid.net/specs/openid-connect-discovery-1_0.html) for the OIDC provider's metadata. */
  openIdConnectUrl: string;
}

/** Defines a security scheme using mTLS authentication. */
export interface MutualTlsSecurityScheme {
  /** An optional description for the security scheme. */
  description: string;
}

/** Defines the configuration for the supported OAuth 2.0 flows. */
export interface OAuthFlows {
  flow?:
    | //
    /** Configuration for the OAuth Authorization Code flow. */
    { $case: "authorizationCode"; value: AuthorizationCodeOAuthFlow }
    | //
    /** Configuration for the OAuth Client Credentials flow. */
    { $case: "clientCredentials"; value: ClientCredentialsOAuthFlow }
    | //
    /** Deprecated: Use Authorization Code + PKCE instead. */
    { $case: "implicit"; value: ImplicitOAuthFlow }
    | //
    /** Deprecated: Use Authorization Code + PKCE or Device Code. */
    { $case: "password"; value: PasswordOAuthFlow }
    | //
    /** Configuration for the OAuth Device Code flow. */
    { $case: "deviceCode"; value: DeviceCodeOAuthFlow }
    | undefined;
}

/** Defines configuration details for the OAuth 2.0 Authorization Code flow. */
export interface AuthorizationCodeOAuthFlow {
  /** The authorization URL to be used for this flow. */
  authorizationUrl: string;
  /** The token URL to be used for this flow. */
  tokenUrl: string;
  /** The URL to be used for obtaining refresh tokens. */
  refreshUrl: string;
  /** The available scopes for the OAuth2 security scheme. */
  scopes: { [key: string]: string };
  /**
   * Indicates if PKCE (RFC 7636) is required for this flow.
   * PKCE should always be used for public clients and is recommended for all clients.
   */
  pkceRequired: boolean;
}

export interface AuthorizationCodeOAuthFlow_ScopesEntry {
  key: string;
  value: string;
}

/** Defines configuration details for the OAuth 2.0 Client Credentials flow. */
export interface ClientCredentialsOAuthFlow {
  /** The token URL to be used for this flow. */
  tokenUrl: string;
  /** The URL to be used for obtaining refresh tokens. */
  refreshUrl: string;
  /** The available scopes for the OAuth2 security scheme. */
  scopes: { [key: string]: string };
}

export interface ClientCredentialsOAuthFlow_ScopesEntry {
  key: string;
  value: string;
}

/** Deprecated: Use Authorization Code + PKCE instead. */
export interface ImplicitOAuthFlow {
  /**
   * The authorization URL to be used for this flow. This MUST be in the
   * form of a URL. The OAuth2 standard requires the use of TLS
   */
  authorizationUrl: string;
  /**
   * The URL to be used for obtaining refresh tokens. This MUST be in the
   * form of a URL. The OAuth2 standard requires the use of TLS.
   */
  refreshUrl: string;
  /**
   * The available scopes for the OAuth2 security scheme. A map between the
   * scope name and a short description for it. The map MAY be empty.
   */
  scopes: { [key: string]: string };
}

export interface ImplicitOAuthFlow_ScopesEntry {
  key: string;
  value: string;
}

/** Deprecated: Use Authorization Code + PKCE or Device Code. */
export interface PasswordOAuthFlow {
  /**
   * The token URL to be used for this flow. This MUST be in the form of a URL.
   * The OAuth2 standard requires the use of TLS.
   */
  tokenUrl: string;
  /**
   * The URL to be used for obtaining refresh tokens. This MUST be in the
   * form of a URL. The OAuth2 standard requires the use of TLS.
   */
  refreshUrl: string;
  /**
   * The available scopes for the OAuth2 security scheme. A map between the
   * scope name and a short description for it. The map MAY be empty.
   */
  scopes: { [key: string]: string };
}

export interface PasswordOAuthFlow_ScopesEntry {
  key: string;
  value: string;
}

/**
 * Defines configuration details for the OAuth 2.0 Device Code flow (RFC 8628).
 * This flow is designed for input-constrained devices such as IoT devices,
 * and CLI tools where the user authenticates on a separate device.
 */
export interface DeviceCodeOAuthFlow {
  /** The device authorization endpoint URL. */
  deviceAuthorizationUrl: string;
  /** The token URL to be used for this flow. */
  tokenUrl: string;
  /** The URL to be used for obtaining refresh tokens. */
  refreshUrl: string;
  /** The available scopes for the OAuth2 security scheme. */
  scopes: { [key: string]: string };
}

export interface DeviceCodeOAuthFlow_ScopesEntry {
  key: string;
  value: string;
}

/** Represents a request for the `SendMessage` method. */
export interface SendMessageRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The message to send to the agent. */
  message:
    | Message
    | undefined;
  /** Configuration for the send request. */
  configuration:
    | SendMessageConfiguration
    | undefined;
  /** A flexible key-value map for passing additional context or parameters. */
  metadata: { [key: string]: any } | undefined;
}

/** Represents a request for the `GetTask` method. */
export interface GetTaskRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The resource ID of the task to retrieve. */
  id: string;
  /**
   * The maximum number of most recent messages from the task's history to retrieve. An
   * unset value means the client does not impose any limit. A value of zero is
   * a request to not include any messages. The server MUST NOT return more
   * messages than the provided value, but MAY apply a lower limit.
   */
  historyLength?: number | undefined;
}

/** Parameters for listing tasks with optional filtering criteria. */
export interface ListTasksRequest {
  /** Tenant ID, provided as a path parameter. */
  tenant: string;
  /** Filter tasks by context ID to get tasks from a specific conversation or session. */
  contextId: string;
  /** Filter tasks by their current status state. */
  status: TaskState;
  /**
   * The maximum number of tasks to return. The service may return fewer than this value.
   * If unspecified, at most 50 tasks will be returned.
   * The minimum value is 1.
   * The maximum value is 100.
   */
  pageSize?:
    | number
    | undefined;
  /**
   * A page token, received from a previous `ListTasks` call.
   * `ListTasksResponse.next_page_token`.
   * Provide this to retrieve the subsequent page.
   */
  pageToken: string;
  /** The maximum number of messages to include in each task's history. */
  historyLength?:
    | number
    | undefined;
  /**
   * Filter tasks which have a status updated after the provided timestamp in ISO 8601 format (e.g., "2023-10-27T10:00:00Z").
   * Only tasks with a status timestamp time greater than or equal to this value will be returned.
   */
  statusTimestampAfter:
    | string
    | undefined;
  /**
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   */
  includeArtifacts?: boolean | undefined;
}

/** Result object for `ListTasks` method containing an array of tasks and pagination information. */
export interface ListTasksResponse {
  /** Array of tasks matching the specified criteria. */
  tasks: Task[];
  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
  nextPageToken: string;
  /** The page size used for this response. */
  pageSize: number;
  /** Total number of tasks available (before pagination). */
  totalSize: number;
}

/** Represents a request for the `CancelTask` method. */
export interface CancelTaskRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The resource ID of the task to cancel. */
  id: string;
  /** A flexible key-value map for passing additional context or parameters. */
  metadata: { [key: string]: any } | undefined;
}

/** Represents a request for the `GetTaskPushNotificationConfig` method. */
export interface GetTaskPushNotificationConfigRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The parent task resource ID. */
  taskId: string;
  /** The resource ID of the configuration to retrieve. */
  id: string;
}

/** Represents a request for the `DeleteTaskPushNotificationConfig` method. */
export interface DeleteTaskPushNotificationConfigRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The parent task resource ID. */
  taskId: string;
  /** The resource ID of the configuration to delete. */
  id: string;
}

/** Represents a request for the `SubscribeToTask` method. */
export interface SubscribeToTaskRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The resource ID of the task to subscribe to. */
  id: string;
}

/** Represents a request for the `ListTaskPushNotificationConfigs` method. */
export interface ListTaskPushNotificationConfigsRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
  /** The parent task resource ID. */
  taskId: string;
  /** The maximum number of configurations to return. */
  pageSize: number;
  /** A page token received from a previous `ListTaskPushNotificationConfigsRequest` call. */
  pageToken: string;
}

/** Represents a request for the `GetExtendedAgentCard` method. */
export interface GetExtendedAgentCardRequest {
  /** Optional. Tenant ID, provided as a path parameter. */
  tenant: string;
}

/** Represents the response for the `SendMessage` method. */
export interface SendMessageResponse {
  /** The payload of the response. */
  payload?:
    | //
    /** The task created or updated by the message. */
    { $case: "task"; value: Task }
    | //
    /** A message from the agent. */
    { $case: "message"; value: Message }
    | undefined;
}

/** A wrapper object used in streaming operations to encapsulate different types of response data. */
export interface StreamResponse {
  /** The payload of the stream response. */
  payload?:
    | //
    /** A Task object containing the current state of the task. */
    { $case: "task"; value: Task }
    | //
    /** A Message object containing a message from the agent. */
    { $case: "message"; value: Message }
    | //
    /** An event indicating a task status update. */
    { $case: "statusUpdate"; value: TaskStatusUpdateEvent }
    | //
    /** An event indicating a task artifact update. */
    { $case: "artifactUpdate"; value: TaskArtifactUpdateEvent }
    | undefined;
}

/**
 * Represents a successful response for the `ListTaskPushNotificationConfigs`
 * method.
 */
export interface ListTaskPushNotificationConfigsResponse {
  /** The list of push notification configurations. */
  configs: TaskPushNotificationConfig[];
  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
  nextPageToken: string;
}

export const SendMessageConfiguration: MessageFns<SendMessageConfiguration> = {
  fromJSON(object: any): SendMessageConfiguration {
    return {
      acceptedOutputModes: globalThis.Array.isArray(object?.acceptedOutputModes)
        ? object.acceptedOutputModes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.accepted_output_modes)
        ? object.accepted_output_modes.map((e: any) =>
          globalThis.String(e)
        )
        : [],
      taskPushNotificationConfig: isSet(object.taskPushNotificationConfig)
        ? TaskPushNotificationConfig.fromJSON(object.taskPushNotificationConfig)
        : isSet(object.task_push_notification_config)
        ? TaskPushNotificationConfig.fromJSON(object.task_push_notification_config)
        : undefined,
      historyLength: isSet(object.historyLength)
        ? globalThis.Number(object.historyLength)
        : isSet(object.history_length)
        ? globalThis.Number(object.history_length)
        : undefined,
      returnImmediately: isSet(object.returnImmediately)
        ? globalThis.Boolean(object.returnImmediately)
        : isSet(object.return_immediately)
        ? globalThis.Boolean(object.return_immediately)
        : false,
    };
  },

  toJSON(message: SendMessageConfiguration): unknown {
    const obj: any = {};
    if (message.acceptedOutputModes?.length) {
      obj.acceptedOutputModes = message.acceptedOutputModes;
    }
    if (message.taskPushNotificationConfig !== undefined) {
      obj.taskPushNotificationConfig = TaskPushNotificationConfig.toJSON(message.taskPushNotificationConfig);
    }
    if (message.historyLength !== undefined) {
      obj.historyLength = Math.round(message.historyLength);
    }
    if (message.returnImmediately !== false) {
      obj.returnImmediately = message.returnImmediately;
    }
    return obj;
  },
};

export const Task: MessageFns<Task> = {
  fromJSON(object: any): Task {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      contextId: isSet(object.contextId)
        ? globalThis.String(object.contextId)
        : isSet(object.context_id)
        ? globalThis.String(object.context_id)
        : "",
      status: isSet(object.status) ? TaskStatus.fromJSON(object.status) : undefined,
      artifacts: globalThis.Array.isArray(object?.artifacts)
        ? object.artifacts.map((e: any) => Artifact.fromJSON(e))
        : [],
      history: globalThis.Array.isArray(object?.history)
        ? object.history.map((e: any) => Message.fromJSON(e))
        : [],
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message: Task): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.contextId !== "") {
      obj.contextId = message.contextId;
    }
    if (message.status !== undefined) {
      obj.status = TaskStatus.toJSON(message.status);
    }
    if (message.artifacts?.length) {
      obj.artifacts = message.artifacts.map((e) => Artifact.toJSON(e));
    }
    if (message.history?.length) {
      obj.history = message.history.map((e) => Message.toJSON(e));
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },
};

export const TaskStatus: MessageFns<TaskStatus> = {
  fromJSON(object: any): TaskStatus {
    return {
      state: isSet(object.state) ? taskStateFromJSON(object.state) : 0,
      message: isSet(object.message) ? Message.fromJSON(object.message) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : undefined,
    };
  },

  toJSON(message: TaskStatus): unknown {
    const obj: any = {};
    if (message.state !== 0) {
      obj.state = taskStateToJSON(message.state);
    }
    if (message.message !== undefined) {
      obj.message = Message.toJSON(message.message);
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },
};

export const Part: MessageFns<Part> = {
  fromJSON(object: any): Part {
    return {
      content: isSet(object.text)
        ? { $case: "text", value: globalThis.String(object.text) }
        : isSet(object.raw)
        ? { $case: "raw", value: Buffer.from(bytesFromBase64(object.raw)) }
        : isSet(object.url)
        ? { $case: "url", value: globalThis.String(object.url) }
        : isSet(object.data)
        ? { $case: "data", value: object.data }
        : undefined,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      mediaType: isSet(object.mediaType)
        ? globalThis.String(object.mediaType)
        : isSet(object.media_type)
        ? globalThis.String(object.media_type)
        : "",
    };
  },

  toJSON(message: Part): unknown {
    const obj: any = {};
    if (message.content?.$case === "text") {
      obj.text = message.content.value;
    } else if (message.content?.$case === "raw") {
      obj.raw = base64FromBytes(message.content.value);
    } else if (message.content?.$case === "url") {
      obj.url = message.content.value;
    } else if (message.content?.$case === "data") {
      obj.data = message.content.value;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.mediaType !== "") {
      obj.mediaType = message.mediaType;
    }
    return obj;
  },
};

export const Message: MessageFns<Message> = {
  fromJSON(object: any): Message {
    return {
      messageId: isSet(object.messageId)
        ? globalThis.String(object.messageId)
        : isSet(object.message_id)
        ? globalThis.String(object.message_id)
        : "",
      contextId: isSet(object.contextId)
        ? globalThis.String(object.contextId)
        : isSet(object.context_id)
        ? globalThis.String(object.context_id)
        : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      parts: globalThis.Array.isArray(object?.parts)
        ? object.parts.map((e: any) => Part.fromJSON(e))
        : [],
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      extensions: globalThis.Array.isArray(object?.extensions)
        ? object.extensions.map((e: any) => globalThis.String(e))
        : [],
      referenceTaskIds: globalThis.Array.isArray(object?.referenceTaskIds)
        ? object.referenceTaskIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.reference_task_ids)
        ? object.reference_task_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.contextId !== "") {
      obj.contextId = message.contextId;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.parts?.length) {
      obj.parts = message.parts.map((e) => Part.toJSON(e));
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.extensions?.length) {
      obj.extensions = message.extensions;
    }
    if (message.referenceTaskIds?.length) {
      obj.referenceTaskIds = message.referenceTaskIds;
    }
    return obj;
  },
};

export const Artifact: MessageFns<Artifact> = {
  fromJSON(object: any): Artifact {
    return {
      artifactId: isSet(object.artifactId)
        ? globalThis.String(object.artifactId)
        : isSet(object.artifact_id)
        ? globalThis.String(object.artifact_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      parts: globalThis.Array.isArray(object?.parts)
        ? object.parts.map((e: any) => Part.fromJSON(e))
        : [],
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      extensions: globalThis.Array.isArray(object?.extensions)
        ? object.extensions.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Artifact): unknown {
    const obj: any = {};
    if (message.artifactId !== "") {
      obj.artifactId = message.artifactId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.parts?.length) {
      obj.parts = message.parts.map((e) => Part.toJSON(e));
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.extensions?.length) {
      obj.extensions = message.extensions;
    }
    return obj;
  },
};

export const TaskStatusUpdateEvent: MessageFns<TaskStatusUpdateEvent> = {
  fromJSON(object: any): TaskStatusUpdateEvent {
    return {
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      contextId: isSet(object.contextId)
        ? globalThis.String(object.contextId)
        : isSet(object.context_id)
        ? globalThis.String(object.context_id)
        : "",
      status: isSet(object.status) ? TaskStatus.fromJSON(object.status) : undefined,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message: TaskStatusUpdateEvent): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.contextId !== "") {
      obj.contextId = message.contextId;
    }
    if (message.status !== undefined) {
      obj.status = TaskStatus.toJSON(message.status);
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },
};

export const TaskArtifactUpdateEvent: MessageFns<TaskArtifactUpdateEvent> = {
  fromJSON(object: any): TaskArtifactUpdateEvent {
    return {
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      contextId: isSet(object.contextId)
        ? globalThis.String(object.contextId)
        : isSet(object.context_id)
        ? globalThis.String(object.context_id)
        : "",
      artifact: isSet(object.artifact) ? Artifact.fromJSON(object.artifact) : undefined,
      append: isSet(object.append) ? globalThis.Boolean(object.append) : false,
      lastChunk: isSet(object.lastChunk)
        ? globalThis.Boolean(object.lastChunk)
        : isSet(object.last_chunk)
        ? globalThis.Boolean(object.last_chunk)
        : false,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message: TaskArtifactUpdateEvent): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.contextId !== "") {
      obj.contextId = message.contextId;
    }
    if (message.artifact !== undefined) {
      obj.artifact = Artifact.toJSON(message.artifact);
    }
    if (message.append !== false) {
      obj.append = message.append;
    }
    if (message.lastChunk !== false) {
      obj.lastChunk = message.lastChunk;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },
};

export const AuthenticationInfo: MessageFns<AuthenticationInfo> = {
  fromJSON(object: any): AuthenticationInfo {
    return {
      scheme: isSet(object.scheme) ? globalThis.String(object.scheme) : "",
      credentials: isSet(object.credentials) ? globalThis.String(object.credentials) : "",
    };
  },

  toJSON(message: AuthenticationInfo): unknown {
    const obj: any = {};
    if (message.scheme !== "") {
      obj.scheme = message.scheme;
    }
    if (message.credentials !== "") {
      obj.credentials = message.credentials;
    }
    return obj;
  },
};

export const AgentInterface: MessageFns<AgentInterface> = {
  fromJSON(object: any): AgentInterface {
    return {
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      protocolBinding: isSet(object.protocolBinding)
        ? globalThis.String(object.protocolBinding)
        : isSet(object.protocol_binding)
        ? globalThis.String(object.protocol_binding)
        : "",
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      protocolVersion: isSet(object.protocolVersion)
        ? globalThis.String(object.protocolVersion)
        : isSet(object.protocol_version)
        ? globalThis.String(object.protocol_version)
        : "",
    };
  },

  toJSON(message: AgentInterface): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.protocolBinding !== "") {
      obj.protocolBinding = message.protocolBinding;
    }
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.protocolVersion !== "") {
      obj.protocolVersion = message.protocolVersion;
    }
    return obj;
  },
};

export const AgentCard: MessageFns<AgentCard> = {
  fromJSON(object: any): AgentCard {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      supportedInterfaces: globalThis.Array.isArray(object?.supportedInterfaces)
        ? object.supportedInterfaces.map((e: any) => AgentInterface.fromJSON(e))
        : globalThis.Array.isArray(object?.supported_interfaces)
        ? object.supported_interfaces.map((e: any) => AgentInterface.fromJSON(e))
        : [],
      provider: isSet(object.provider) ? AgentProvider.fromJSON(object.provider) : undefined,
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      documentationUrl: isSet(object.documentationUrl)
        ? globalThis.String(object.documentationUrl)
        : isSet(object.documentation_url)
        ? globalThis.String(object.documentation_url)
        : undefined,
      capabilities: isSet(object.capabilities) ? AgentCapabilities.fromJSON(object.capabilities) : undefined,
      securitySchemes: isObject(object.securitySchemes)
        ? (globalThis.Object.entries(object.securitySchemes) as [string, any][]).reduce(
          (acc: { [key: string]: SecurityScheme }, [key, value]: [string, any]) => {
            acc[key] = SecurityScheme.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.security_schemes)
        ? (globalThis.Object.entries(object.security_schemes) as [string, any][]).reduce(
          (acc: { [key: string]: SecurityScheme }, [key, value]: [string, any]) => {
            acc[key] = SecurityScheme.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      securityRequirements: globalThis.Array.isArray(object?.securityRequirements)
        ? object.securityRequirements.map((e: any) => SecurityRequirement.fromJSON(e))
        : globalThis.Array.isArray(object?.security_requirements)
        ? object.security_requirements.map((e: any) => SecurityRequirement.fromJSON(e))
        : [],
      defaultInputModes: globalThis.Array.isArray(object?.defaultInputModes)
        ? object.defaultInputModes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.default_input_modes)
        ? object.default_input_modes.map((e: any) => globalThis.String(e))
        : [],
      defaultOutputModes: globalThis.Array.isArray(object?.defaultOutputModes)
        ? object.defaultOutputModes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.default_output_modes)
        ? object.default_output_modes.map((e: any) => globalThis.String(e))
        : [],
      skills: globalThis.Array.isArray(object?.skills)
        ? object.skills.map((e: any) => AgentSkill.fromJSON(e))
        : [],
      signatures: globalThis.Array.isArray(object?.signatures)
        ? object.signatures.map((e: any) => AgentCardSignature.fromJSON(e))
        : [],
      iconUrl: isSet(object.iconUrl)
        ? globalThis.String(object.iconUrl)
        : isSet(object.icon_url)
        ? globalThis.String(object.icon_url)
        : undefined,
    };
  },

  toJSON(message: AgentCard): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.supportedInterfaces?.length) {
      obj.supportedInterfaces = message.supportedInterfaces.map((e) => AgentInterface.toJSON(e));
    }
    if (message.provider !== undefined) {
      obj.provider = AgentProvider.toJSON(message.provider);
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.documentationUrl !== undefined) {
      obj.documentationUrl = message.documentationUrl;
    }
    if (message.capabilities !== undefined) {
      obj.capabilities = AgentCapabilities.toJSON(message.capabilities);
    }
    if (message.securitySchemes) {
      const entries = globalThis.Object.entries(message.securitySchemes) as [string, SecurityScheme][];
      if (entries.length > 0) {
        obj.securitySchemes = {};
        entries.forEach(([k, v]) => {
          obj.securitySchemes[k] = SecurityScheme.toJSON(v);
        });
      }
    }
    if (message.securityRequirements?.length) {
      obj.securityRequirements = message.securityRequirements.map((e) => SecurityRequirement.toJSON(e));
    }
    if (message.defaultInputModes?.length) {
      obj.defaultInputModes = message.defaultInputModes;
    }
    if (message.defaultOutputModes?.length) {
      obj.defaultOutputModes = message.defaultOutputModes;
    }
    if (message.skills?.length) {
      obj.skills = message.skills.map((e) => AgentSkill.toJSON(e));
    }
    if (message.signatures?.length) {
      obj.signatures = message.signatures.map((e) => AgentCardSignature.toJSON(e));
    }
    if (message.iconUrl !== undefined) {
      obj.iconUrl = message.iconUrl;
    }
    return obj;
  },
};

export const AgentCard_SecuritySchemesEntry: MessageFns<AgentCard_SecuritySchemesEntry> = {
  fromJSON(object: any): AgentCard_SecuritySchemesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? SecurityScheme.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: AgentCard_SecuritySchemesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = SecurityScheme.toJSON(message.value);
    }
    return obj;
  },
};

export const AgentProvider: MessageFns<AgentProvider> = {
  fromJSON(object: any): AgentProvider {
    return {
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      organization: isSet(object.organization) ? globalThis.String(object.organization) : "",
    };
  },

  toJSON(message: AgentProvider): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.organization !== "") {
      obj.organization = message.organization;
    }
    return obj;
  },
};

export const AgentCapabilities: MessageFns<AgentCapabilities> = {
  fromJSON(object: any): AgentCapabilities {
    return {
      streaming: isSet(object.streaming) ? globalThis.Boolean(object.streaming) : undefined,
      pushNotifications: isSet(object.pushNotifications)
        ? globalThis.Boolean(object.pushNotifications)
        : isSet(object.push_notifications)
        ? globalThis.Boolean(object.push_notifications)
        : undefined,
      extensions: globalThis.Array.isArray(object?.extensions)
        ? object.extensions.map((e: any) => AgentExtension.fromJSON(e))
        : [],
      extendedAgentCard: isSet(object.extendedAgentCard)
        ? globalThis.Boolean(object.extendedAgentCard)
        : isSet(object.extended_agent_card)
        ? globalThis.Boolean(object.extended_agent_card)
        : undefined,
    };
  },

  toJSON(message: AgentCapabilities): unknown {
    const obj: any = {};
    if (message.streaming !== undefined) {
      obj.streaming = message.streaming;
    }
    if (message.pushNotifications !== undefined) {
      obj.pushNotifications = message.pushNotifications;
    }
    if (message.extensions?.length) {
      obj.extensions = message.extensions.map((e) => AgentExtension.toJSON(e));
    }
    if (message.extendedAgentCard !== undefined) {
      obj.extendedAgentCard = message.extendedAgentCard;
    }
    return obj;
  },
};

export const AgentExtension: MessageFns<AgentExtension> = {
  fromJSON(object: any): AgentExtension {
    return {
      uri: isSet(object.uri) ? globalThis.String(object.uri) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      required: isSet(object.required) ? globalThis.Boolean(object.required) : false,
      params: isObject(object.params) ? object.params : undefined,
    };
  },

  toJSON(message: AgentExtension): unknown {
    const obj: any = {};
    if (message.uri !== "") {
      obj.uri = message.uri;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.required !== false) {
      obj.required = message.required;
    }
    if (message.params !== undefined) {
      obj.params = message.params;
    }
    return obj;
  },
};

export const AgentSkill: MessageFns<AgentSkill> = {
  fromJSON(object: any): AgentSkill {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      examples: globalThis.Array.isArray(object?.examples) ? object.examples.map((e: any) => globalThis.String(e)) : [],
      inputModes: globalThis.Array.isArray(object?.inputModes)
        ? object.inputModes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.input_modes)
        ? object.input_modes.map((e: any) => globalThis.String(e))
        : [],
      outputModes: globalThis.Array.isArray(object?.outputModes)
        ? object.outputModes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.output_modes)
        ? object.output_modes.map((e: any) => globalThis.String(e))
        : [],
      securityRequirements: globalThis.Array.isArray(object?.securityRequirements)
        ? object.securityRequirements.map((e: any) => SecurityRequirement.fromJSON(e))
        : globalThis.Array.isArray(object?.security_requirements)
        ? object.security_requirements.map((e: any) => SecurityRequirement.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AgentSkill): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.examples?.length) {
      obj.examples = message.examples;
    }
    if (message.inputModes?.length) {
      obj.inputModes = message.inputModes;
    }
    if (message.outputModes?.length) {
      obj.outputModes = message.outputModes;
    }
    if (message.securityRequirements?.length) {
      obj.securityRequirements = message.securityRequirements.map((e) => SecurityRequirement.toJSON(e));
    }
    return obj;
  },
};

export const AgentCardSignature: MessageFns<AgentCardSignature> = {
  fromJSON(object: any): AgentCardSignature {
    return {
      protected: isSet(object.protected) ? globalThis.String(object.protected) : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      header: isObject(object.header) ? object.header : undefined,
    };
  },

  toJSON(message: AgentCardSignature): unknown {
    const obj: any = {};
    if (message.protected !== "") {
      obj.protected = message.protected;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.header !== undefined) {
      obj.header = message.header;
    }
    return obj;
  },
};

export const TaskPushNotificationConfig: MessageFns<TaskPushNotificationConfig> = {
  fromJSON(object: any): TaskPushNotificationConfig {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      authentication: isSet(object.authentication) ? AuthenticationInfo.fromJSON(object.authentication) : undefined,
    };
  },

  toJSON(message: TaskPushNotificationConfig): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.authentication !== undefined) {
      obj.authentication = AuthenticationInfo.toJSON(message.authentication);
    }
    return obj;
  },
};

export const StringList: MessageFns<StringList> = {
  fromJSON(object: any): StringList {
    return { list: globalThis.Array.isArray(object?.list) ? object.list.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: StringList): unknown {
    const obj: any = {};
    if (message.list?.length) {
      obj.list = message.list;
    }
    return obj;
  },
};

export const SecurityRequirement: MessageFns<SecurityRequirement> = {
  fromJSON(object: any): SecurityRequirement {
    return {
      schemes: isObject(object.schemes)
        ? (globalThis.Object.entries(object.schemes) as [string, any][]).reduce(
          (acc: { [key: string]: StringList }, [key, value]: [string, any]) => {
            acc[key] = StringList.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: SecurityRequirement): unknown {
    const obj: any = {};
    if (message.schemes) {
      const entries = globalThis.Object.entries(message.schemes) as [string, StringList][];
      if (entries.length > 0) {
        obj.schemes = {};
        entries.forEach(([k, v]) => {
          obj.schemes[k] = StringList.toJSON(v);
        });
      }
    }
    return obj;
  },
};

export const SecurityRequirement_SchemesEntry: MessageFns<SecurityRequirement_SchemesEntry> = {
  fromJSON(object: any): SecurityRequirement_SchemesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? StringList.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: SecurityRequirement_SchemesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = StringList.toJSON(message.value);
    }
    return obj;
  },
};

export const SecurityScheme: MessageFns<SecurityScheme> = {
  fromJSON(object: any): SecurityScheme {
    return {
      scheme: isSet(object.apiKeySecurityScheme)
        ? { $case: "apiKeySecurityScheme", value: APIKeySecurityScheme.fromJSON(object.apiKeySecurityScheme) }
        : isSet(object.api_key_security_scheme)
        ? { $case: "apiKeySecurityScheme", value: APIKeySecurityScheme.fromJSON(object.api_key_security_scheme) }
        : isSet(object.httpAuthSecurityScheme)
        ? { $case: "httpAuthSecurityScheme", value: HTTPAuthSecurityScheme.fromJSON(object.httpAuthSecurityScheme) }
        : isSet(object.http_auth_security_scheme)
        ? { $case: "httpAuthSecurityScheme", value: HTTPAuthSecurityScheme.fromJSON(object.http_auth_security_scheme) }
        : isSet(object.oauth2SecurityScheme)
        ? { $case: "oauth2SecurityScheme", value: OAuth2SecurityScheme.fromJSON(object.oauth2SecurityScheme) }
        : isSet(object.oauth2_security_scheme)
        ? { $case: "oauth2SecurityScheme", value: OAuth2SecurityScheme.fromJSON(object.oauth2_security_scheme) }
        : isSet(object.openIdConnectSecurityScheme)
        ? {
          $case: "openIdConnectSecurityScheme",
          value: OpenIdConnectSecurityScheme.fromJSON(object.openIdConnectSecurityScheme),
        }
        : isSet(object.open_id_connect_security_scheme)
        ? {
          $case: "openIdConnectSecurityScheme",
          value: OpenIdConnectSecurityScheme.fromJSON(object.open_id_connect_security_scheme),
        }
        : isSet(object.mtlsSecurityScheme)
        ? { $case: "mtlsSecurityScheme", value: MutualTlsSecurityScheme.fromJSON(object.mtlsSecurityScheme) }
        : isSet(object.mtls_security_scheme)
        ? { $case: "mtlsSecurityScheme", value: MutualTlsSecurityScheme.fromJSON(object.mtls_security_scheme) }
        : undefined,
    };
  },

  toJSON(message: SecurityScheme): unknown {
    const obj: any = {};
    if (message.scheme?.$case === "apiKeySecurityScheme") {
      obj.apiKeySecurityScheme = APIKeySecurityScheme.toJSON(message.scheme.value);
    } else if (message.scheme?.$case === "httpAuthSecurityScheme") {
      obj.httpAuthSecurityScheme = HTTPAuthSecurityScheme.toJSON(message.scheme.value);
    } else if (message.scheme?.$case === "oauth2SecurityScheme") {
      obj.oauth2SecurityScheme = OAuth2SecurityScheme.toJSON(message.scheme.value);
    } else if (message.scheme?.$case === "openIdConnectSecurityScheme") {
      obj.openIdConnectSecurityScheme = OpenIdConnectSecurityScheme.toJSON(message.scheme.value);
    } else if (message.scheme?.$case === "mtlsSecurityScheme") {
      obj.mtlsSecurityScheme = MutualTlsSecurityScheme.toJSON(message.scheme.value);
    }
    return obj;
  },
};

export const APIKeySecurityScheme: MessageFns<APIKeySecurityScheme> = {
  fromJSON(object: any): APIKeySecurityScheme {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: APIKeySecurityScheme): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },
};

export const HTTPAuthSecurityScheme: MessageFns<HTTPAuthSecurityScheme> = {
  fromJSON(object: any): HTTPAuthSecurityScheme {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      scheme: isSet(object.scheme) ? globalThis.String(object.scheme) : "",
      bearerFormat: isSet(object.bearerFormat)
        ? globalThis.String(object.bearerFormat)
        : isSet(object.bearer_format)
        ? globalThis.String(object.bearer_format)
        : "",
    };
  },

  toJSON(message: HTTPAuthSecurityScheme): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.scheme !== "") {
      obj.scheme = message.scheme;
    }
    if (message.bearerFormat !== "") {
      obj.bearerFormat = message.bearerFormat;
    }
    return obj;
  },
};

export const OAuth2SecurityScheme: MessageFns<OAuth2SecurityScheme> = {
  fromJSON(object: any): OAuth2SecurityScheme {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      flows: isSet(object.flows) ? OAuthFlows.fromJSON(object.flows) : undefined,
      oauth2MetadataUrl: isSet(object.oauth2MetadataUrl)
        ? globalThis.String(object.oauth2MetadataUrl)
        : isSet(object.oauth2_metadata_url)
        ? globalThis.String(object.oauth2_metadata_url)
        : "",
    };
  },

  toJSON(message: OAuth2SecurityScheme): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.flows !== undefined) {
      obj.flows = OAuthFlows.toJSON(message.flows);
    }
    if (message.oauth2MetadataUrl !== "") {
      obj.oauth2MetadataUrl = message.oauth2MetadataUrl;
    }
    return obj;
  },
};

export const OpenIdConnectSecurityScheme: MessageFns<OpenIdConnectSecurityScheme> = {
  fromJSON(object: any): OpenIdConnectSecurityScheme {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      openIdConnectUrl: isSet(object.openIdConnectUrl)
        ? globalThis.String(object.openIdConnectUrl)
        : isSet(object.open_id_connect_url)
        ? globalThis.String(object.open_id_connect_url)
        : "",
    };
  },

  toJSON(message: OpenIdConnectSecurityScheme): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.openIdConnectUrl !== "") {
      obj.openIdConnectUrl = message.openIdConnectUrl;
    }
    return obj;
  },
};

export const MutualTlsSecurityScheme: MessageFns<MutualTlsSecurityScheme> = {
  fromJSON(object: any): MutualTlsSecurityScheme {
    return { description: isSet(object.description) ? globalThis.String(object.description) : "" };
  },

  toJSON(message: MutualTlsSecurityScheme): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },
};

export const OAuthFlows: MessageFns<OAuthFlows> = {
  fromJSON(object: any): OAuthFlows {
    return {
      flow: isSet(object.authorizationCode)
        ? { $case: "authorizationCode", value: AuthorizationCodeOAuthFlow.fromJSON(object.authorizationCode) }
        : isSet(object.authorization_code)
        ? { $case: "authorizationCode", value: AuthorizationCodeOAuthFlow.fromJSON(object.authorization_code) }
        : isSet(object.clientCredentials)
        ? { $case: "clientCredentials", value: ClientCredentialsOAuthFlow.fromJSON(object.clientCredentials) }
        : isSet(object.client_credentials)
        ? { $case: "clientCredentials", value: ClientCredentialsOAuthFlow.fromJSON(object.client_credentials) }
        : isSet(object.implicit)
        ? { $case: "implicit", value: ImplicitOAuthFlow.fromJSON(object.implicit) }
        : isSet(object.password)
        ? { $case: "password", value: PasswordOAuthFlow.fromJSON(object.password) }
        : isSet(object.deviceCode)
        ? { $case: "deviceCode", value: DeviceCodeOAuthFlow.fromJSON(object.deviceCode) }
        : isSet(object.device_code)
        ? { $case: "deviceCode", value: DeviceCodeOAuthFlow.fromJSON(object.device_code) }
        : undefined,
    };
  },

  toJSON(message: OAuthFlows): unknown {
    const obj: any = {};
    if (message.flow?.$case === "authorizationCode") {
      obj.authorizationCode = AuthorizationCodeOAuthFlow.toJSON(message.flow.value);
    } else if (message.flow?.$case === "clientCredentials") {
      obj.clientCredentials = ClientCredentialsOAuthFlow.toJSON(message.flow.value);
    } else if (message.flow?.$case === "implicit") {
      obj.implicit = ImplicitOAuthFlow.toJSON(message.flow.value);
    } else if (message.flow?.$case === "password") {
      obj.password = PasswordOAuthFlow.toJSON(message.flow.value);
    } else if (message.flow?.$case === "deviceCode") {
      obj.deviceCode = DeviceCodeOAuthFlow.toJSON(message.flow.value);
    }
    return obj;
  },
};

export const AuthorizationCodeOAuthFlow: MessageFns<AuthorizationCodeOAuthFlow> = {
  fromJSON(object: any): AuthorizationCodeOAuthFlow {
    return {
      authorizationUrl: isSet(object.authorizationUrl)
        ? globalThis.String(object.authorizationUrl)
        : isSet(object.authorization_url)
        ? globalThis.String(object.authorization_url)
        : "",
      tokenUrl: isSet(object.tokenUrl)
        ? globalThis.String(object.tokenUrl)
        : isSet(object.token_url)
        ? globalThis.String(object.token_url)
        : "",
      refreshUrl: isSet(object.refreshUrl)
        ? globalThis.String(object.refreshUrl)
        : isSet(object.refresh_url)
        ? globalThis.String(object.refresh_url)
        : "",
      scopes: isObject(object.scopes)
        ? (globalThis.Object.entries(object.scopes) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      pkceRequired: isSet(object.pkceRequired)
        ? globalThis.Boolean(object.pkceRequired)
        : isSet(object.pkce_required)
        ? globalThis.Boolean(object.pkce_required)
        : false,
    };
  },

  toJSON(message: AuthorizationCodeOAuthFlow): unknown {
    const obj: any = {};
    if (message.authorizationUrl !== "") {
      obj.authorizationUrl = message.authorizationUrl;
    }
    if (message.tokenUrl !== "") {
      obj.tokenUrl = message.tokenUrl;
    }
    if (message.refreshUrl !== "") {
      obj.refreshUrl = message.refreshUrl;
    }
    if (message.scopes) {
      const entries = globalThis.Object.entries(message.scopes) as [string, string][];
      if (entries.length > 0) {
        obj.scopes = {};
        entries.forEach(([k, v]) => {
          obj.scopes[k] = v;
        });
      }
    }
    if (message.pkceRequired !== false) {
      obj.pkceRequired = message.pkceRequired;
    }
    return obj;
  },
};

export const AuthorizationCodeOAuthFlow_ScopesEntry: MessageFns<AuthorizationCodeOAuthFlow_ScopesEntry> = {
  fromJSON(object: any): AuthorizationCodeOAuthFlow_ScopesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: AuthorizationCodeOAuthFlow_ScopesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },
};

export const ClientCredentialsOAuthFlow: MessageFns<ClientCredentialsOAuthFlow> = {
  fromJSON(object: any): ClientCredentialsOAuthFlow {
    return {
      tokenUrl: isSet(object.tokenUrl)
        ? globalThis.String(object.tokenUrl)
        : isSet(object.token_url)
        ? globalThis.String(object.token_url)
        : "",
      refreshUrl: isSet(object.refreshUrl)
        ? globalThis.String(object.refreshUrl)
        : isSet(object.refresh_url)
        ? globalThis.String(object.refresh_url)
        : "",
      scopes: isObject(object.scopes)
        ? (globalThis.Object.entries(object.scopes) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ClientCredentialsOAuthFlow): unknown {
    const obj: any = {};
    if (message.tokenUrl !== "") {
      obj.tokenUrl = message.tokenUrl;
    }
    if (message.refreshUrl !== "") {
      obj.refreshUrl = message.refreshUrl;
    }
    if (message.scopes) {
      const entries = globalThis.Object.entries(message.scopes) as [string, string][];
      if (entries.length > 0) {
        obj.scopes = {};
        entries.forEach(([k, v]) => {
          obj.scopes[k] = v;
        });
      }
    }
    return obj;
  },
};

export const ClientCredentialsOAuthFlow_ScopesEntry: MessageFns<ClientCredentialsOAuthFlow_ScopesEntry> = {
  fromJSON(object: any): ClientCredentialsOAuthFlow_ScopesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ClientCredentialsOAuthFlow_ScopesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },
};

export const ImplicitOAuthFlow: MessageFns<ImplicitOAuthFlow> = {
  fromJSON(object: any): ImplicitOAuthFlow {
    return {
      authorizationUrl: isSet(object.authorizationUrl)
        ? globalThis.String(object.authorizationUrl)
        : isSet(object.authorization_url)
        ? globalThis.String(object.authorization_url)
        : "",
      refreshUrl: isSet(object.refreshUrl)
        ? globalThis.String(object.refreshUrl)
        : isSet(object.refresh_url)
        ? globalThis.String(object.refresh_url)
        : "",
      scopes: isObject(object.scopes)
        ? (globalThis.Object.entries(object.scopes) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ImplicitOAuthFlow): unknown {
    const obj: any = {};
    if (message.authorizationUrl !== "") {
      obj.authorizationUrl = message.authorizationUrl;
    }
    if (message.refreshUrl !== "") {
      obj.refreshUrl = message.refreshUrl;
    }
    if (message.scopes) {
      const entries = globalThis.Object.entries(message.scopes) as [string, string][];
      if (entries.length > 0) {
        obj.scopes = {};
        entries.forEach(([k, v]) => {
          obj.scopes[k] = v;
        });
      }
    }
    return obj;
  },
};

export const ImplicitOAuthFlow_ScopesEntry: MessageFns<ImplicitOAuthFlow_ScopesEntry> = {
  fromJSON(object: any): ImplicitOAuthFlow_ScopesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ImplicitOAuthFlow_ScopesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },
};

export const PasswordOAuthFlow: MessageFns<PasswordOAuthFlow> = {
  fromJSON(object: any): PasswordOAuthFlow {
    return {
      tokenUrl: isSet(object.tokenUrl)
        ? globalThis.String(object.tokenUrl)
        : isSet(object.token_url)
        ? globalThis.String(object.token_url)
        : "",
      refreshUrl: isSet(object.refreshUrl)
        ? globalThis.String(object.refreshUrl)
        : isSet(object.refresh_url)
        ? globalThis.String(object.refresh_url)
        : "",
      scopes: isObject(object.scopes)
        ? (globalThis.Object.entries(object.scopes) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: PasswordOAuthFlow): unknown {
    const obj: any = {};
    if (message.tokenUrl !== "") {
      obj.tokenUrl = message.tokenUrl;
    }
    if (message.refreshUrl !== "") {
      obj.refreshUrl = message.refreshUrl;
    }
    if (message.scopes) {
      const entries = globalThis.Object.entries(message.scopes) as [string, string][];
      if (entries.length > 0) {
        obj.scopes = {};
        entries.forEach(([k, v]) => {
          obj.scopes[k] = v;
        });
      }
    }
    return obj;
  },
};

export const PasswordOAuthFlow_ScopesEntry: MessageFns<PasswordOAuthFlow_ScopesEntry> = {
  fromJSON(object: any): PasswordOAuthFlow_ScopesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: PasswordOAuthFlow_ScopesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },
};

export const DeviceCodeOAuthFlow: MessageFns<DeviceCodeOAuthFlow> = {
  fromJSON(object: any): DeviceCodeOAuthFlow {
    return {
      deviceAuthorizationUrl: isSet(object.deviceAuthorizationUrl)
        ? globalThis.String(object.deviceAuthorizationUrl)
        : isSet(object.device_authorization_url)
        ? globalThis.String(object.device_authorization_url)
        : "",
      tokenUrl: isSet(object.tokenUrl)
        ? globalThis.String(object.tokenUrl)
        : isSet(object.token_url)
        ? globalThis.String(object.token_url)
        : "",
      refreshUrl: isSet(object.refreshUrl)
        ? globalThis.String(object.refreshUrl)
        : isSet(object.refresh_url)
        ? globalThis.String(object.refresh_url)
        : "",
      scopes: isObject(object.scopes)
        ? (globalThis.Object.entries(object.scopes) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DeviceCodeOAuthFlow): unknown {
    const obj: any = {};
    if (message.deviceAuthorizationUrl !== "") {
      obj.deviceAuthorizationUrl = message.deviceAuthorizationUrl;
    }
    if (message.tokenUrl !== "") {
      obj.tokenUrl = message.tokenUrl;
    }
    if (message.refreshUrl !== "") {
      obj.refreshUrl = message.refreshUrl;
    }
    if (message.scopes) {
      const entries = globalThis.Object.entries(message.scopes) as [string, string][];
      if (entries.length > 0) {
        obj.scopes = {};
        entries.forEach(([k, v]) => {
          obj.scopes[k] = v;
        });
      }
    }
    return obj;
  },
};

export const DeviceCodeOAuthFlow_ScopesEntry: MessageFns<DeviceCodeOAuthFlow_ScopesEntry> = {
  fromJSON(object: any): DeviceCodeOAuthFlow_ScopesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: DeviceCodeOAuthFlow_ScopesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },
};

export const SendMessageRequest: MessageFns<SendMessageRequest> = {
  fromJSON(object: any): SendMessageRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      message: isSet(object.message) ? Message.fromJSON(object.message) : undefined,
      configuration: isSet(object.configuration) ? SendMessageConfiguration.fromJSON(object.configuration) : undefined,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message: SendMessageRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.message !== undefined) {
      obj.message = Message.toJSON(message.message);
    }
    if (message.configuration !== undefined) {
      obj.configuration = SendMessageConfiguration.toJSON(message.configuration);
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },
};

export const GetTaskRequest: MessageFns<GetTaskRequest> = {
  fromJSON(object: any): GetTaskRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      historyLength: isSet(object.historyLength)
        ? globalThis.Number(object.historyLength)
        : isSet(object.history_length)
        ? globalThis.Number(object.history_length)
        : undefined,
    };
  },

  toJSON(message: GetTaskRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.historyLength !== undefined) {
      obj.historyLength = Math.round(message.historyLength);
    }
    return obj;
  },
};

export const ListTasksRequest: MessageFns<ListTasksRequest> = {
  fromJSON(object: any): ListTasksRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      contextId: isSet(object.contextId)
        ? globalThis.String(object.contextId)
        : isSet(object.context_id)
        ? globalThis.String(object.context_id)
        : "",
      status: isSet(object.status) ? taskStateFromJSON(object.status) : 0,
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : undefined,
      pageToken: isSet(object.pageToken)
        ? globalThis.String(object.pageToken)
        : isSet(object.page_token)
        ? globalThis.String(object.page_token)
        : "",
      historyLength: isSet(object.historyLength)
        ? globalThis.Number(object.historyLength)
        : isSet(object.history_length)
        ? globalThis.Number(object.history_length)
        : undefined,
      statusTimestampAfter: isSet(object.statusTimestampAfter)
        ? globalThis.String(object.statusTimestampAfter)
        : isSet(object.status_timestamp_after)
        ? globalThis.String(object.status_timestamp_after)
        : undefined,
      includeArtifacts: isSet(object.includeArtifacts)
        ? globalThis.Boolean(object.includeArtifacts)
        : isSet(object.include_artifacts)
        ? globalThis.Boolean(object.include_artifacts)
        : undefined,
    };
  },

  toJSON(message: ListTasksRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.contextId !== "") {
      obj.contextId = message.contextId;
    }
    if (message.status !== 0) {
      obj.status = taskStateToJSON(message.status);
    }
    if (message.pageSize !== undefined) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== "") {
      obj.pageToken = message.pageToken;
    }
    if (message.historyLength !== undefined) {
      obj.historyLength = Math.round(message.historyLength);
    }
    if (message.statusTimestampAfter !== undefined) {
      obj.statusTimestampAfter = message.statusTimestampAfter;
    }
    if (message.includeArtifacts !== undefined) {
      obj.includeArtifacts = message.includeArtifacts;
    }
    return obj;
  },
};

export const ListTasksResponse: MessageFns<ListTasksResponse> = {
  fromJSON(object: any): ListTasksResponse {
    return {
      tasks: globalThis.Array.isArray(object?.tasks) ? object.tasks.map((e: any) => Task.fromJSON(e)) : [],
      nextPageToken: isSet(object.nextPageToken)
        ? globalThis.String(object.nextPageToken)
        : isSet(object.next_page_token)
        ? globalThis.String(object.next_page_token)
        : "",
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
      totalSize: isSet(object.totalSize)
        ? globalThis.Number(object.totalSize)
        : isSet(object.total_size)
        ? globalThis.Number(object.total_size)
        : 0,
    };
  },

  toJSON(message: ListTasksResponse): unknown {
    const obj: any = {};
    if (message.tasks?.length) {
      obj.tasks = message.tasks.map((e) => Task.toJSON(e));
    }
    if (message.nextPageToken !== "") {
      obj.nextPageToken = message.nextPageToken;
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.totalSize !== 0) {
      obj.totalSize = Math.round(message.totalSize);
    }
    return obj;
  },
};

export const CancelTaskRequest: MessageFns<CancelTaskRequest> = {
  fromJSON(object: any): CancelTaskRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message: CancelTaskRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },
};

export const GetTaskPushNotificationConfigRequest: MessageFns<GetTaskPushNotificationConfigRequest> = {
  fromJSON(object: any): GetTaskPushNotificationConfigRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: GetTaskPushNotificationConfigRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },
};

export const DeleteTaskPushNotificationConfigRequest: MessageFns<DeleteTaskPushNotificationConfigRequest> = {
  fromJSON(object: any): DeleteTaskPushNotificationConfigRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: DeleteTaskPushNotificationConfigRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },
};

export const SubscribeToTaskRequest: MessageFns<SubscribeToTaskRequest> = {
  fromJSON(object: any): SubscribeToTaskRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
    };
  },

  toJSON(message: SubscribeToTaskRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },
};

export const ListTaskPushNotificationConfigsRequest: MessageFns<ListTaskPushNotificationConfigsRequest> = {
  fromJSON(object: any): ListTaskPushNotificationConfigsRequest {
    return {
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
      taskId: isSet(object.taskId)
        ? globalThis.String(object.taskId)
        : isSet(object.task_id)
        ? globalThis.String(object.task_id)
        : "",
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
      pageToken: isSet(object.pageToken)
        ? globalThis.String(object.pageToken)
        : isSet(object.page_token)
        ? globalThis.String(object.page_token)
        : "",
    };
  },

  toJSON(message: ListTaskPushNotificationConfigsRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.pageToken !== "") {
      obj.pageToken = message.pageToken;
    }
    return obj;
  },
};

export const GetExtendedAgentCardRequest: MessageFns<GetExtendedAgentCardRequest> = {
  fromJSON(object: any): GetExtendedAgentCardRequest {
    return { tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "" };
  },

  toJSON(message: GetExtendedAgentCardRequest): unknown {
    const obj: any = {};
    if (message.tenant !== "") {
      obj.tenant = message.tenant;
    }
    return obj;
  },
};

export const SendMessageResponse: MessageFns<SendMessageResponse> = {
  fromJSON(object: any): SendMessageResponse {
    return {
      payload: isSet(object.task)
        ? { $case: "task", value: Task.fromJSON(object.task) }
        : isSet(object.message)
        ? { $case: "message", value: Message.fromJSON(object.message) }
        : undefined,
    };
  },

  toJSON(message: SendMessageResponse): unknown {
    const obj: any = {};
    if (message.payload?.$case === "task") {
      obj.task = Task.toJSON(message.payload.value);
    } else if (message.payload?.$case === "message") {
      obj.message = Message.toJSON(message.payload.value);
    }
    return obj;
  },
};

export const StreamResponse: MessageFns<StreamResponse> = {
  fromJSON(object: any): StreamResponse {
    return {
      payload: isSet(object.task)
        ? { $case: "task", value: Task.fromJSON(object.task) }
        : isSet(object.message)
        ? { $case: "message", value: Message.fromJSON(object.message) }
        : isSet(object.statusUpdate)
        ? { $case: "statusUpdate", value: TaskStatusUpdateEvent.fromJSON(object.statusUpdate) }
        : isSet(object.status_update)
        ? { $case: "statusUpdate", value: TaskStatusUpdateEvent.fromJSON(object.status_update) }
        : isSet(object.artifactUpdate)
        ? { $case: "artifactUpdate", value: TaskArtifactUpdateEvent.fromJSON(object.artifactUpdate) }
        : isSet(object.artifact_update)
        ? { $case: "artifactUpdate", value: TaskArtifactUpdateEvent.fromJSON(object.artifact_update) }
        : undefined,
    };
  },

  toJSON(message: StreamResponse): unknown {
    const obj: any = {};
    if (message.payload?.$case === "task") {
      obj.task = Task.toJSON(message.payload.value);
    } else if (message.payload?.$case === "message") {
      obj.message = Message.toJSON(message.payload.value);
    } else if (message.payload?.$case === "statusUpdate") {
      obj.statusUpdate = TaskStatusUpdateEvent.toJSON(message.payload.value);
    } else if (message.payload?.$case === "artifactUpdate") {
      obj.artifactUpdate = TaskArtifactUpdateEvent.toJSON(message.payload.value);
    }
    return obj;
  },
};

export const ListTaskPushNotificationConfigsResponse: MessageFns<ListTaskPushNotificationConfigsResponse> = {
  fromJSON(object: any): ListTaskPushNotificationConfigsResponse {
    return {
      configs: globalThis.Array.isArray(object?.configs)
        ? object.configs.map((e: any) => TaskPushNotificationConfig.fromJSON(e))
        : [],
      nextPageToken: isSet(object.nextPageToken)
        ? globalThis.String(object.nextPageToken)
        : isSet(object.next_page_token)
        ? globalThis.String(object.next_page_token)
        : "",
    };
  },

  toJSON(message: ListTaskPushNotificationConfigsResponse): unknown {
    const obj: any = {};
    if (message.configs?.length) {
      obj.configs = message.configs.map((e) => TaskPushNotificationConfig.toJSON(e));
    }
    if (message.nextPageToken !== "") {
      obj.nextPageToken = message.nextPageToken;
    }
    return obj;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
}
