import {
  Task,
  TaskState,
  TaskStatusUpdateEvent,
  TaskArtifactUpdateEvent,
  Artifact,
  Role,
} from '../../../index.js';
import {
  AgentExecutor,
  RequestContext,
  ExecutionEventBus,
  AgentEvent,
} from '../../../server/index.js';

/**
 * DatabaseAgentExecutor implements the agent execution logic for the
 * database-backed agent sample.
 *
 * It executes tasks through standard lifecycle stages:
 * 1. Initial task snapshot (submitted)
 * 2. Status update (working)
 * 3. Result artifact
 * 4. Final status update (completed)
 *
 * Every event published to the eventBus is persisted into SQLite by
 * DatabaseTaskStore.
 */
export class DatabaseAgentExecutor implements AgentExecutor {
  public cancelTask = async (taskId: string, _eventBus: ExecutionEventBus): Promise<void> => {
    console.log(`[DatabaseAgentExecutor] Cancellation requested for task ${taskId}`);
  };

  async execute(requestContext: RequestContext, eventBus: ExecutionEventBus): Promise<void> {
    const userMessage = requestContext.userMessage;
    const existingTask = requestContext.task;
    const taskId = requestContext.taskId;
    const contextId = requestContext.contextId;

    console.log(
      `[DatabaseAgentExecutor] Processing message ${userMessage.messageId} for task ${taskId}`
    );

    // 1. Publish initial Task snapshot.
    const taskSnapshot: Task = existingTask ?? {
      id: taskId,
      contextId,
      status: {
        state: TaskState.TASK_STATE_SUBMITTED,
        timestamp: new Date().toISOString(),
        message: undefined,
      },
      artifacts: [],
      history: [userMessage],
      metadata: userMessage.metadata,
    };
    eventBus.publish(AgentEvent.task(taskSnapshot));

    // 2. Publish "working" status update.
    const workingStatusUpdate: TaskStatusUpdateEvent = {
      taskId,
      contextId,
      status: {
        state: TaskState.TASK_STATE_WORKING,
        message: {
          role: Role.ROLE_AGENT,
          messageId: crypto.randomUUID(),
          parts: [
            {
              content: { $case: 'text', value: 'Processing task and storing in database...' },
              metadata: undefined,
              filename: '',
              mediaType: 'text/plain',
            },
          ],
          taskId,
          contextId,
          extensions: [],
          metadata: {},
          referenceTaskIds: [],
        },
        timestamp: new Date().toISOString(),
      },
      metadata: {},
    };
    eventBus.publish(AgentEvent.statusUpdate(workingStatusUpdate));

    // Simulate work.
    await new Promise((resolve) => setTimeout(resolve, 500));

    // 3. Publish an artifact with the agent's response.
    const userQuery =
      userMessage.parts.find((part) => part.content?.$case === 'text')?.content?.value ??
      'Task request';

    const responseText =
      `Agent Analysis Complete:\n` +
      `Successfully processed request: "${userQuery}".\n` +
      `Execution result, history, and status have been persisted to SQLite via DatabaseTaskStore.`;

    const resultArtifact: Artifact = {
      artifactId: crypto.randomUUID(),
      name: 'Agent Execution Result',
      description: 'Result generated by DatabaseAgentExecutor and stored in SQLite.',
      parts: [
        {
          content: {
            $case: 'text',
            value: responseText,
          },
          metadata: undefined,
          filename: '',
          mediaType: 'text/plain',
        },
      ],
      metadata: undefined,
      extensions: [],
    };

    const artifactUpdate: TaskArtifactUpdateEvent = {
      taskId,
      contextId,
      artifact: resultArtifact,
      lastChunk: true,
      append: false,
      metadata: undefined,
    };
    eventBus.publish(AgentEvent.artifactUpdate(artifactUpdate));

    // 4. Publish final completed status.
    const finalUpdate: TaskStatusUpdateEvent = {
      taskId,
      contextId,
      status: {
        state: TaskState.TASK_STATE_COMPLETED,
        timestamp: new Date().toISOString(),
        message: undefined,
      },
      metadata: {},
    };
    eventBus.publish(AgentEvent.statusUpdate(finalUpdate));

    console.log(`[DatabaseAgentExecutor] Task ${taskId} completed and persisted.`);
  }
}
